apiVersion: v1alpha
kind: playwright
sauce:
  region: eu-central-1
  concurrency: 10 # Controls how many suites are executed at the same time.
  metadata:
    tags:
      - e2e
      - release team
      - saucectl
      - playwright
playwright:
  version: package.json # See https://docs.saucelabs.com/web-apps/automated-testing/playwright/#supported-testing-platforms for a list of supported versions.
  configFile: playwright.config.ts # See https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#configfile for a list of supported configuration files.
# Controls what files are available in the context of a test run (unless explicitly excluded by .sauceignore).
rootDir: ./
suites:
  # - name: "Firefox Win"
  #   platformName: "Windows 11"
  #   screenResolution: "1440x900"
  #   testMatch: [".*.ts"]
  #   params:
  #     browserName: "firefox"
  #     project: "firefox" 
  - name: "Chromium Mac"
    platformName: "macOS 12"
    screenResolution: "1440x900"
    testMatch: [".*.ts"]
    params:
      browserName: "chromium"
      project: "chromium"
  # - name: "Webkit Win"
  #   platformName: "Windows 11"
  #   screenResolution: "1440x900"
  #   testMatch: [".*.ts"]
  #   params:
  #     browserName: "webkit"
  #     project: "webkit"
# Controls what artifacts to fetch when the suites have finished.
# artifacts:
#   download:
#     when: always
#     match:
#       - console.log
#     directory: ./artifacts/

reporters:
  spotlight: # Prints an overview of failed or otherwise interesting jobs.
    enabled: true
# npm:
#   packages:
#     "@playwright/test": "1.52.0"
#     "typescript": "latest"
#     "ts-node": "latest"
#     "@axe-core/playwright": "latest"
#   strictSSL: true
#   registry: https://registry.npmjs.org